### ISSUE TITLE
CSRF Token has been associated to this client

### ISSUE THREAD

**Issue by ojaynico** [raphaelDL/spring-webflux-security-jwt#8]
Why do i get this message when i use postman. Curl is working perfectly though.

**Comment by raphaelDL** [comment]
Hi,
can you share steps to reproduce this?

**Comment by ojaynico** [comment]
When i start the application it starts successfully.
When i run this in terminal i get a response with the jwt token.
curl -v  -u user:user localhost:8080/login
But when i try to post login data to localhost:8080/login in json format, i get the "CSRF Token has been associated to this client".
The json format i am using in postman is 
{"username": "user", "password": "user"}

Simply the app isnt returning any token when i use postman, it only works using curl.

**Comment by raphaelDL** [comment]
this
`curl -v -u user:user localhost:8080/login`

In postman should be something like:

`GET localhost:8080/login` 

then in the Authorization tab, select Basic auth, it will display two fields for credentials. This will add the Authorization header that you can check in the Headers tab.

The approach you are using won't work because there isn't a method to handle a POST action in the MessageController

**Comment by ojaynico** [comment]
Thank you very much, it has worked. i was used to post method. 
Thanks once again for the repo.
